package contracts

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/google/jsonschema-go/jsonschema"
	"gopkg.in/yaml.v3"

	"github.com/rus-lan/bogoslav-analytics/apps/internal/artifact"
	"github.com/rus-lan/bogoslav-analytics/apps/internal/mcptool"
)

// OpenAPIVersion is the openapi field value this package emits (TZ.md
// section 10: OpenAPI 3.1).
const OpenAPIVersion = "3.1.0"

// generatedHeader is prepended, byte for byte, to every call to
// Generate's output. It carries no variable content (no timestamp, no
// hostname, nothing map-order-dependent), so it never breaks the
// zero-diff regeneration guarantee (TZ.md section 12.16).
const generatedHeader = "" +
	"# Code generated by apps/internal/contracts; DO NOT EDIT.\n" +
	"# Regenerate: make -C apps contracts (or: go generate ./internal/contracts, from apps/).\n"

// infoDescription is the OpenAPI document's info.description: the one
// place inside the document itself (as opposed to only in this
// package's own doc.go) that records what is generated, why paths is
// empty, and which two output shapes are honestly left out and why
// (TZ.md section 10; see doc.go for the full reasoning).
const infoDescription = "" +
	"GitLab review-activity analytics (bogoslavAnalytics). This document ships no REST API: " +
	"access is CLI and MCP-over-stdio only, so paths is intentionally empty (TZ.md section 13). " +
	"Every schema under components/schemas is generated at build time by " +
	"apps/internal/contracts, via jsonschema.ForType on the same Go types " +
	"apps/cmd/bogoslav-mcp's mcp.AddTool calls use to infer each tool's inputSchema by " +
	"reflection -- one generation, two consumers, never a hand-typed duplicate (TZ.md section 10). " +
	"Included: the six MCP tool input types (find_mrs, get_comments, get_classify_batch, " +
	"save_labels, filter_comments, get_stats) and the four artifact document types (mr_list, " +
	"comment_list, labeled_comments, filtered_comments). Left out, honestly rather than faked: " +
	"get_classify_batch's output schema, because its Go type embeds *jsonschema.Schema, which is " +
	"self-referential and jsonschema.ForType cannot resolve (the same reason that tool is " +
	"registered with mcp.AddTool's Out type parameter as \"any\", not that type); and the other " +
	"five tools' output types, which live in package main of apps/cmd/bogoslav-mcp and so cannot " +
	"be imported by any generator, by any other package, at all -- a Go language rule, not an " +
	"oversight."

// schemaEntry names one Go type this package emits a components/schemas
// entry for. Name becomes the schema's key; it is derived from the Go
// type itself (reflect.Type.Name()), not typed out twice, so the two
// can never quietly drift apart.
type schemaEntry struct {
	Name string
	Type reflect.Type
}

func newSchemaEntry(t reflect.Type) schemaEntry {
	return schemaEntry{Name: t.Name(), Type: t}
}

// schemaEntries lists every Go type this package emits a schema for:
// the six MCP tool input types (TZ.md section 7.2) and the four
// artifact document types (TZ.md section 4). Order here only decides
// the order errors are reported in -- the emitted document's
// components/schemas keys are sorted independently (see Generate).
func schemaEntries() []schemaEntry {
	return []schemaEntry{
		newSchemaEntry(reflect.TypeFor[mcptool.FindMRsInput]()),
		newSchemaEntry(reflect.TypeFor[mcptool.GetCommentsInput]()),
		newSchemaEntry(reflect.TypeFor[mcptool.GetClassifyBatchInput]()),
		newSchemaEntry(reflect.TypeFor[mcptool.SaveLabelsInput]()),
		newSchemaEntry(reflect.TypeFor[mcptool.FilterCommentsInput]()),
		newSchemaEntry(reflect.TypeFor[mcptool.GetStatsInput]()),
		newSchemaEntry(reflect.TypeFor[artifact.MRList]()),
		newSchemaEntry(reflect.TypeFor[artifact.CommentList]()),
		newSchemaEntry(reflect.TypeFor[artifact.LabeledComments]()),
		newSchemaEntry(reflect.TypeFor[artifact.FilteredComments]()),
	}
}

// openAPIDocument is the root OpenAPI 3.1 object this package marshals
// to YAML. Field order here is the field order Generate emits (yaml.v3
// does not reorder struct fields); map fields are sorted independently
// (see Generate and gopkg.in/yaml.v3's own map-key sort on Marshal).
type openAPIDocument struct {
	OpenAPI    string            `yaml:"openapi"`
	Info       openAPIInfo       `yaml:"info"`
	Paths      map[string]any    `yaml:"paths"`
	Components openAPIComponents `yaml:"components"`
}

type openAPIInfo struct {
	Title       string `yaml:"title"`
	Version     string `yaml:"version"`
	Description string `yaml:"description"`
}

type openAPIComponents struct {
	// Schemas is keyed by schemaEntry.Name. gopkg.in/yaml.v3 sorts map
	// keys on Marshal, so this is deterministic without this package
	// sorting it a second time -- Generate still builds the key list
	// itself in sorted order first, so that guarantee is never implicit
	// alone (see Generate).
	Schemas map[string]*yaml.Node `yaml:"schemas"`
}

// Generate builds the full contracts/openapi.yaml document, byte for
// byte deterministically: the same Go types always produce the same
// output (TZ.md section 12.16 -- regenerating must be a zero diff).
// Determinism holds because every source of nondeterminism is closed
// off explicitly: schemaEntries lists types in a fixed order, schema
// property order comes from jsonschema-go's own PropertyOrder (fixed
// per type, mirrored by Schema.MarshalJSON), components/schemas keys
// are collected into a sorted slice before being placed in the (still
// separately sorted-on-Marshal) map, and generatedHeader/infoDescription
// carry no variable content -- no timestamp, no hostname, nothing.
func Generate() ([]byte, error) {
	entries := schemaEntries()
	names := make([]string, 0, len(entries))
	byName := make(map[string]schemaEntry, len(entries))
	for _, e := range entries {
		if _, dup := byName[e.Name]; dup {
			return nil, fmt.Errorf("contracts: duplicate schema name %q", e.Name)
		}
		byName[e.Name] = e
		names = append(names, e.Name)
	}
	sort.Strings(names)

	schemas := make(map[string]*yaml.Node, len(names))
	for _, name := range names {
		e := byName[name]
		s, err := jsonschema.ForType(e.Type, &jsonschema.ForOptions{})
		if err != nil {
			return nil, fmt.Errorf("contracts: schema for %s (%s): %w", e.Name, e.Type, err)
		}
		node, err := schemaNode(s)
		if err != nil {
			return nil, fmt.Errorf("contracts: encode schema for %s: %w", e.Name, err)
		}
		schemas[name] = node
	}

	if err := checkGetClassifyBatchOutputCycle(); err != nil {
		return nil, err
	}

	doc := openAPIDocument{
		OpenAPI: OpenAPIVersion,
		Info: openAPIInfo{
			Title:       "bogoslavAnalytics",
			Version:     "1.0.0",
			Description: infoDescription,
		},
		Paths:      map[string]any{},
		Components: openAPIComponents{Schemas: schemas},
	}

	body, err := yaml.Marshal(doc)
	if err != nil {
		return nil, fmt.Errorf("contracts: marshal openapi document: %w", err)
	}

	out := make([]byte, 0, len(generatedHeader)+len(body))
	out = append(out, []byte(generatedHeader)...)
	out = append(out, body...)
	return out, nil
}

// checkGetClassifyBatchOutputCycle confirms that
// jsonschema.ForType(mcptool.GetClassifyBatchOutput) still fails for
// the one reason this package's design accepts (a self-reference cycle
// through *jsonschema.Schema -- see doc.go): Generate refuses to run
// if that assumption stops holding, rather than silently going on
// omitting a schema that may have become inferable, or masking an
// unrelated new failure as if it were the known one.
func checkGetClassifyBatchOutputCycle() error {
	_, err := jsonschema.ForType(reflect.TypeFor[mcptool.GetClassifyBatchOutput](), &jsonschema.ForOptions{})
	if err == nil {
		return fmt.Errorf("contracts: jsonschema.ForType(GetClassifyBatchOutput) unexpectedly " +
			"succeeded; the self-reference cycle documented in doc.go seems to be gone -- " +
			"update Generate to emit this schema instead of omitting it")
	}
	if !strings.Contains(err.Error(), "cycle detected") {
		return fmt.Errorf("contracts: jsonschema.ForType(GetClassifyBatchOutput) failed for an "+
			"unexpected reason (want a self-reference cycle, see doc.go): %w", err)
	}
	return nil
}

// schemaNode converts s into a *yaml.Node ready to embed in an
// openAPIComponents.Schemas map. It goes through s's own MarshalJSON
// (the same deterministic, PropertyOrder-driven encoding
// classify.ResultSchema()'s tests already prove round-trips cleanly)
// rather than a plain Go map: JSON is valid YAML, so parsing the JSON
// bytes as YAML keeps every property's exact declaration order and
// every scalar's exact literal text, with none of the float64
// round-tripping a decode into map[string]any would otherwise risk for
// large integers (not a concern for any schema this package emits
// today -- none of these Go types has a uint64, float32/64, int8/16/32
// or uint/uint8/16/32 field, so jsonschema-go never sets a Minimum or
// Maximum bound on any of them -- but avoided here anyway rather than
// relied upon).
func schemaNode(s *jsonschema.Schema) (*yaml.Node, error) {
	data, err := json.Marshal(s)
	if err != nil {
		return nil, err
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, err
	}
	if len(doc.Content) != 1 {
		return nil, fmt.Errorf("contracts: unexpected YAML document shape for schema (want exactly one root node, got %d)", len(doc.Content))
	}
	node := doc.Content[0]
	clearNodeStyle(node)
	return node, nil
}

// clearNodeStyle resets every node's Style to its zero value,
// recursively. yaml.Unmarshal of JSON bytes tags every node with a flow
// style (JSON's own style); left alone, re-marshaling would render the
// whole schema as a single flow-style ({...}) line instead of readable
// block-style YAML. This is purely a rendering choice -- flow and block
// style parse back to the identical value -- made once here so every
// schema in the document renders the same, readable way.
func clearNodeStyle(n *yaml.Node) {
	if n == nil {
		return
	}
	n.Style = 0
	for _, c := range n.Content {
		clearNodeStyle(c)
	}
}
