package artifact

import (
	"bytes"
	"fmt"
	"html/template"
	"time"
)

// htmlStyle is the single inline stylesheet shared by every rendered
// page. There is no external stylesheet, font, or script: the html
// format is meant to be opened offline, attached to tickets, and
// emailed (TZ.md section 4; see also the html format's own write-only
// rule next to FormatHTML).
const htmlStyle = `
:root {
  color-scheme: light dark;
  --bg: #ffffff;
  --fg: #1a1a1a;
  --muted: #5f6368;
  --border: #d9dcdf;
  --card-bg: #f6f7f9;
  --highlight-bg: #eef4ff;
  --highlight-border: #7aa7ff;
  --link: #0b5fff;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #14161a;
    --fg: #e8e9ec;
    --muted: #9aa0a6;
    --border: #33373d;
    --card-bg: #1d2025;
    --highlight-bg: #16233a;
    --highlight-border: #3a6fd8;
    --link: #6ea8ff;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  padding: 1.5rem;
  background: var(--bg);
  color: var(--fg);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
  line-height: 1.5;
  overflow-x: hidden;
}
a { color: var(--link); }
h1 { margin: 0 0 0.25rem; font-size: 1.4rem; }
h2 { font-size: 1.1rem; margin: 1.5rem 0 0.5rem; }
.meta, .query {
  border: 1px solid var(--border);
  background: var(--card-bg);
  border-radius: 8px;
  padding: 0.75rem 1rem;
  margin-bottom: 1rem;
}
dl { display: grid; grid-template-columns: max-content 1fr; gap: 0.15rem 0.75rem; margin: 0; }
dt { color: var(--muted); }
dd { margin: 0; }
dt.highlight, dd.highlight {
  background: var(--highlight-bg);
  border: 1px solid var(--highlight-border);
  border-radius: 4px;
  padding: 0.1rem 0.4rem;
  font-weight: 600;
}
.provenance {
  border: 1px solid var(--highlight-border);
  background: var(--highlight-bg);
  border-radius: 8px;
  padding: 0.75rem 1rem;
  margin-bottom: 1rem;
}
.provenance h2 { margin-top: 0; }
.table-scroll { overflow-x: auto; border: 1px solid var(--border); border-radius: 8px; }
table { border-collapse: collapse; width: 100%; min-width: 40rem; }
th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid var(--border); white-space: nowrap; }
tbody tr:last-child td { border-bottom: none; }
.count { color: var(--muted); font-weight: normal; font-size: 0.9em; }
.comment {
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 0.6rem 0.9rem;
  margin: 0.5rem 0;
  background: var(--card-bg);
}
.comment header {
  display: flex;
  gap: 0.75rem;
  color: var(--muted);
  font-size: 0.9em;
  margin-bottom: 0.35rem;
}
.comment .author { font-weight: 600; color: var(--fg); }
.comment .body { white-space: pre-wrap; word-break: break-word; }
.label-badge {
  display: inline-block;
  border: 1px solid var(--highlight-border);
  background: var(--highlight-bg);
  border-radius: 999px;
  padding: 0.05rem 0.6rem;
  font-size: 0.85em;
}
footer { margin-top: 2rem; color: var(--muted); font-size: 0.85em; }
`

// htmlFuncs are the template helper functions available to every
// rendered page.
var htmlFuncs = template.FuncMap{
	"fmtTime": func(t time.Time) string {
		if t.IsZero() {
			return ""
		}
		return t.Format(time.RFC3339)
	},
	"groupCommentsByMR":   groupCommentsByMR,
	"groupLabeledByLabel": groupLabeledByLabel,
}

// renderHTML parses templateSource (the shared layout plus one kind's
// "query" and "content" definitions) with html/template — never
// text/template, since comment bodies and web URLs are untrusted,
// attacker-influenced GitLab content that must go through contextual
// auto-escaping — and executes it against data.
func renderHTML(templateSource string, data any) ([]byte, error) {
	tmpl, err := template.New("layout").Funcs(htmlFuncs).Parse(templateSource)
	if err != nil {
		return nil, fmt.Errorf("render html: parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("render html: execute template: %w", err)
	}
	return buf.Bytes(), nil
}

// htmlLayout is the shared page shell: doctype, inline style, the
// common header (schema_version, kind, source), and slots for a
// kind-specific "query" section and "content" section. Every per-kind
// template text below is this layout plus its own {{define "query"}}
// and {{define "content"}} blocks.
const htmlLayout = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>bogoslavAnalytics artifact -- {{.Kind}}</title>
<style>` + htmlStyle + `</style>
</head>
<body>
<header>
  <h1>{{.Kind}}</h1>
  <dl class="meta">
    <dt>schema_version</dt><dd>{{.SchemaVersion}}</dd>
    <dt>source.gitlab_url</dt><dd>{{.Source.GitlabURL}}</dd>
    <dt>source.fetched_at</dt><dd>{{fmtTime .Source.FetchedAt}}</dd>
  </dl>
</header>
{{template "query" .}}
{{template "content" .}}
<footer>generated by bogoslavAnalytics -- self-contained report, safe to view offline</footer>
</body>
</html>
`

// labeledItemsContentTemplate is the "content" section shared by
// labeled_comments and filtered_comments: both hold the same
// LabeledCommentItem rows and both are grouped BY LABEL rather than by
// merge request.
const labeledItemsContentTemplate = `
{{define "content"}}
<section class="content">
{{$groups := groupLabeledByLabel .Items}}
  <h2>Comments <span class="count">({{len .Items}} across {{len $groups}} label{{if ne (len $groups) 1}}s{{end}})</span></h2>
  {{range $groups}}
    <h3><span class="label-badge">{{.Label}}</span> <span class="count">({{len .Items}})</span></h3>
    {{range .Items}}
      <article class="comment">
        <header><span class="author">{{.Author.Username}}</span><time>{{fmtTime .CreatedAt}}</time><span>MR !{{.MRIID}}</span></header>
        <div class="body">{{.Body}}</div>
      </article>
    {{end}}
  {{end}}
</section>
{{end}}
`
